/******************************************************
 * This is the main file for the mips1 ArchC model    *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 
// Rodolfo editou aqui
//
const char *project_name="mips1";
const char *project_file="mips1.ac";
const char *archc_version="2.0beta1";
const char *archc_options="-abi -dy ";

#include  <systemc.h>
#include  "mips1.H"
#include  "ac_tlm_mem.h"
#include  "bar_mem.h"
#include "hardware_pow.h"

using user::ac_tlm_mem;

int sc_main(int ac, char *av[])
{

  //!  ISA simulator
  mips1 mips1_proc1("mips1");
  mips1 mips1_proc2("mips2");
  mips1 mips1_proc3("mips3");
  mips1 mips1_proc4("mips4");
  mips1 mips1_proc5("mips5");
  mips1 mips1_proc6("mips6");
  mips1 mips1_proc7("mips7");
  mips1 mips1_proc8("mips8");
  ac_tlm_mem mem("mem");
  user::hardware_pow hdp("hardware_pow1");
  user::bar_mem bar("bar_mem1");
  
  bar.DM_port(mem.target_export);
  bar.HDP_port(hdp.target_export);

#ifdef AC_DEBUG
  ac_trace("mips1_proc1.trace");
#endif

  mips1_proc1.DM_port(bar.target_export2);
  mips1_proc2.DM_port(bar.target_export1);
  mips1_proc3.DM_port(bar.target_export3);
  mips1_proc4.DM_port(bar.target_export4);
  mips1_proc5.DM_port(bar.target_export5);
  mips1_proc6.DM_port(bar.target_export6);
  mips1_proc7.DM_port(bar.target_export7);
  mips1_proc8.DM_port(bar.target_export8);

  char * program = av[1];

  mips1_proc1.init(ac, av);

  av[1] = program;
  mips1_proc2.init(ac, av);

  av[1] = program;
  mips1_proc3.init(ac, av);

  av[1] = program;
  mips1_proc4.init(ac, av);

  av[1] = program;
  mips1_proc5.init(ac, av);

  av[1] = program;
  mips1_proc6.init(ac, av);

  av[1] = program;
  mips1_proc7.init(ac, av);

  av[1] = program;
  mips1_proc8.init(ac, av);
  cerr << endl;

  sc_start();

  mips1_proc1.PrintStat();
  mips1_proc2.PrintStat();
  mips1_proc3.PrintStat();
  mips1_proc4.PrintStat();
  mips1_proc5.PrintStat();
  mips1_proc6.PrintStat();
  mips1_proc7.PrintStat();
  mips1_proc8.PrintStat();
  cerr << endl;

#ifdef AC_STATS
  mips1_proc1.ac_sim_stats.time = sc_simulation_time();
  mips1_proc1.ac_sim_stats.print();
#endif 

#ifdef AC_DEBUG
  ac_close_trace();
#endif
  return 0;
  /*return (mips1_proc1.ac_exit_status | 
          mips1_proc2.ac_exit_status |
          mips1_proc3.ac_exit_status |
          mips1_proc4.ac_exit_status |
          mips1_proc5.ac_exit_status |
          mips1_proc6.ac_exit_status |
          mips1_proc7.ac_exit_status |
          mips1_proc8.ac_exit_status);*/
}
